version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 5 * * *"
    exclude-paths:
      - "Brave/**"
      - "Chrome/**"
      - "Chromium/**"
      - "Edge/**"
      - "Firefox/**"
      - "Opera/**"
      - "Vivaldi/**"
      
- package-ecosystem: "docker"
  directory: "/Brave"
  schedule:
    interval: "daily"

- package-ecosystem: "docker"
  directory: "/Chrome"
  schedule:
    interval: "daily"

- package-ecosystem: "docker"
  directory: "/Chromium"
  schedule:
    interval: "daily"

- package-ecosystem: "docker"
  directory: "/Edge"
  schedule:
    interval: "daily"

- package-ecosystem: "docker"
  directory: "/Firefox"
  schedule:
    interval: "daily"

- package-ecosystem: "docker"
  directory: "/Opera"
  schedule:
    interval: "daily"

- package-ecosystem: "docker"
  directory: "/Vivaldi"
  schedule:
    interval: "daily"
