version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 5 * * *"
    exclude-paths:
      - "Brave/**"
      - "Chrome/**"
      - "Chromium/**"
      - "Edge/**"
      - "Firefox/**"
      - "Opera/**"
      - "Vivaldi/**"
      
  - package-ecosystem: "docker"
    directory: "/Brave/Dockerfile"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Chrome/Dockerfile"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Chromium/Dockerfile"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Edge/Dockerfile"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Firefox/Dockerfile"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Opera/Dockerfile"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Vivaldi/Dockerfile"
    schedule:
      interval: "weekly"
