name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Brave/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Opera/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Chrome/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Chromium/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Firefox/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Vivaldi/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Edge/Dockerfile --tag my-image-name:$(date +%s)
